export type CatalogSeedItem=readonly [section:string,category:string,name:string,unit:string,labor:number,material:number];

export const catalogSeed:readonly CatalogSeedItem[]=[
 ["Preparatory works","Site preparation","Site survey and marking","job",180,20],
 ["Preparatory works","Site preparation","Protect existing finishes","m²",4,3],
 ["Preparatory works","Site preparation","Construction site cleanup","hour",18,2],
 ["Preparatory works","Temporary works","Temporary power and lighting","job",220,90],
 ["Preparatory works","Temporary works","Scaffolding assembly","m²",9,4],
 ["Demolition works","Walls and partitions","Remove brick partition","m²",18,3],
 ["Demolition works","Walls and partitions","Remove drywall partition","m²",11,2],
 ["Demolition works","Flooring","Remove laminate or parquet","m²",7,1],
 ["Demolition works","Flooring","Remove ceramic floor tile","m²",10,2],
 ["Demolition works","Flooring","Remove floor screed","m²",16,4],
 ["Demolition works","Ceilings","Remove suspended ceiling","m²",8,1],
 ["Demolition works","Wall finishes","Remove wall tile","m²",10,2],
 ["Demolition works","Wall finishes","Remove plaster","m²",9,2],
 ["Demolition works","Openings","Remove interior door","pcs",25,2],
 ["Demolition works","Openings","Remove window","pcs",45,5],
 ["Demolition works","Utilities","Remove plumbing fixtures","pcs",28,2],
 ["Demolition works","Utilities","Remove electrical wiring","point",12,1],
 ["Demolition works","Waste","Load and remove construction waste","m³",45,35],
 ["Structural works","Earthworks","Manual excavation","m³",32,0],
 ["Structural works","Earthworks","Mechanical excavation","m³",12,18],
 ["Structural works","Foundations","Lean concrete base","m³",75,110],
 ["Structural works","Foundations","Reinforced concrete footing","m³",120,145],
 ["Structural works","Concrete","Install reinforcement","kg",0.9,1.2],
 ["Structural works","Concrete","Install formwork","m²",22,12],
 ["Structural works","Concrete","Pour concrete slab","m³",95,125],
 ["Structural works","Masonry","Brick wall","m²",36,32],
 ["Structural works","Masonry","Concrete block wall","m²",31,25],
 ["Structural works","Masonry","Aerated concrete block wall","m²",29,24],
 ["Structural works","Steel structures","Install structural steel","kg",2.4,2.8],
 ["Exterior works","Roofing","Install metal roofing","m²",27,34],
 ["Exterior works","Roofing","Install asphalt shingles","m²",24,28],
 ["Exterior works","Roofing","Install roof membrane","m²",14,12],
 ["Exterior works","Roofing","Install gutters and downpipes","m",18,16],
 ["Exterior works","Facade","Cement render to facade","m²",25,17],
 ["Exterior works","Facade","Decorative facade plaster","m²",19,18],
 ["Exterior works","Facade","Install ventilated facade cladding","m²",38,42],
 ["Exterior works","Insulation","External wall insulation","m²",18,19],
 ["Exterior works","Waterproofing","Foundation waterproofing","m²",16,14],
 ["Exterior works","Windows","Install window","pcs",120,35],
 ["Exterior works","Exterior doors","Install exterior door","pcs",160,40],
 ["Interior works","Partitions","Drywall partition","m²",18,16],
 ["Interior works","Partitions","Moisture-resistant drywall partition","m²",21,20],
 ["Interior works","Plastering","Wall plaster","m²",14,6],
 ["Interior works","Plastering","Ceiling skim coat","m²",16,5],
 ["Interior works","Plastering","Wall skim coat","m²",11,4],
 ["Interior works","Painting","Prime walls or ceilings","m²",3,2],
 ["Interior works","Painting","Paint walls, two coats","m²",8,5],
 ["Interior works","Painting","Paint ceilings, two coats","m²",9,5],
 ["Interior works","Ceilings","Suspended drywall ceiling","m²",20,18],
 ["Interior works","Ceilings","Armstrong suspended ceiling","m²",17,19],
 ["Interior works","Flooring","Level floor with screed","m²",16,11],
 ["Interior works","Flooring","Self-leveling floor compound","m²",9,8],
 ["Interior works","Flooring","Install laminate flooring","m²",15,11],
 ["Interior works","Flooring","Install parquet board","m²",28,25],
 ["Interior works","Flooring","Install solid hardwood flooring","m²",34,32],
 ["Interior works","Flooring","Install linoleum","m²",11,9],
 ["Interior works","Flooring","Install vinyl flooring","m²",14,15],
 ["Interior works","Flooring","Install skirting board","m",6,5],
 ["Interior works","Tiling","Waterproof wet area","m²",12,8],
 ["Interior works","Tiling","Install ceramic wall tile","m²",28,14],
 ["Interior works","Tiling","Install porcelain floor tile","m²",32,18],
 ["Interior works","Tiling","Install mosaic tile","m²",42,24],
 ["Interior works","Doors","Install interior door","pcs",95,25],
 ["Interior works","Doors","Install door trim","m",8,5],
 ["Interior works","Carpentry","Install window sill","m",18,15],
 ["Interior works","Carpentry","Install decorative wall panels","m²",24,28],
 ["Engineering systems","Electrical","Install electrical cable","m",3.5,2.5],
 ["Engineering systems","Electrical","Install outlet or switch point","point",24,12],
 ["Engineering systems","Electrical","Install lighting point","point",28,15],
 ["Engineering systems","Electrical","Install distribution board","pcs",180,120],
 ["Engineering systems","Low voltage","Install data cable","m",3,2],
 ["Engineering systems","Low voltage","Install CCTV camera","pcs",65,55],
 ["Engineering systems","Plumbing","Install cold or hot water pipe","m",16,9],
 ["Engineering systems","Plumbing","Install drainage pipe","m",18,12],
 ["Engineering systems","Plumbing","Install plumbing fixture","pcs",65,12],
 ["Engineering systems","Plumbing","Install concealed toilet frame","pcs",110,45],
 ["Engineering systems","Heating","Install radiator","pcs",75,35],
 ["Engineering systems","Heating","Install underfloor heating","m²",18,20],
 ["Engineering systems","HVAC","Install split air conditioner","pcs",180,90],
 ["Engineering systems","HVAC","Install ventilation duct","m",22,18],
 ["Landscaping","Paving","Install concrete paving blocks","m²",22,24],
 ["Landscaping","Paving","Install natural stone paving","m²",32,38],
 ["Landscaping","Drainage","Install surface drainage channel","m",24,21],
 ["Landscaping","Fencing","Install metal fence","m",38,45],
 ["Landscaping","Soft landscaping","Prepare and seed lawn","m²",7,5],
 ["Landscaping","Soft landscaping","Plant shrub","pcs",12,15],
 ["Other works","Logistics","Delivery and handling","trip",45,20],
 ["Other works","General labor","General laborer","hour",18,0],
 ["Other works","Equipment","Small equipment rental","day",15,35]
];
