import {catalogLabels} from "./catalog-i18n.ts";
export type Language="en"|"ru"|"es";
type Pair={ru:string;es:string};
export const labels:Record<string,Pair>={
 "Dashboard":{ru:"Панель",es:"Panel"},"Clients":{ru:"Клиенты",es:"Clientes"},"Projects":{ru:"Проекты",es:"Proyectos"},"Catalog":{ru:"Каталог работ",es:"Catálogo"},"Materials":{ru:"Материалы",es:"Materiales"},"Settings":{ru:"Настройки",es:"Ajustes"},
 "Your business at a glance":{ru:"Главные показатели вашего бизнеса",es:"Tu negocio de un vistazo"},"Manage clients":{ru:"Управление клиентами",es:"Gestionar clientes"},"Manage projects":{ru:"Управление проектами",es:"Gestionar proyectos"},"Manage catalog":{ru:"Управление каталогом",es:"Gestionar catálogo"},"Manage materials":{ru:"Управление материалами",es:"Gestionar materiales"},"Manage settings":{ru:"Управление настройками",es:"Gestionar ajustes"},
 "New Estimate":{ru:"Новая смета",es:"Nuevo presupuesto"},"BUSINESS PLAN":{ru:"ТАРИФ BUSINESS",es:"PLAN BUSINESS"},"All features unlocked":{ru:"Все функции доступны",es:"Todas las funciones activas"},"Team, analytics & branding":{ru:"Команда, аналитика и бренд",es:"Equipo, analítica y marca"},
 "START AN ESTIMATE":{ru:"НАЧАТЬ РАСЧЁТ",es:"CREAR PRESUPUESTO"},"Turn site notes into a profitable quote.":{ru:"Превратите замеры в прибыльную смету.",es:"Convierte las notas de obra en una oferta rentable."},"Build the cost, protect your margin, and send a clean client proposal.":{ru:"Рассчитайте себестоимость, защитите маржу и отправьте клиенту понятное предложение.",es:"Calcula costes, protege el margen y envía una propuesta clara."},"Quick calculator":{ru:"Быстрый расчёт",es:"Cálculo rápido"},"Detailed estimate":{ru:"Подробная смета",es:"Presupuesto detallado"},
 "Estimate":{ru:"Смета",es:"Presupuesto"},"Estimates":{ru:"Сметы",es:"Presupuestos"},"Sent proposals":{ru:"Отправлено",es:"Enviadas"},"Accepted":{ru:"Принято",es:"Aceptadas"},"Revenue":{ru:"Выручка",es:"Ingresos"},"Profit":{ru:"Прибыль",es:"Beneficio"},"Conversion":{ru:"Конверсия",es:"Conversión"},"after costs":{ru:"после расходов",es:"después de costes"},
 "Recent projects":{ru:"Последние проекты",es:"Proyectos recientes"},"Open an estimate and continue where you left off.":{ru:"Откройте смету и продолжите работу.",es:"Abre un presupuesto y continúa donde lo dejaste."},"Profit snapshot":{ru:"Прибыль",es:"Resumen de beneficio"},"Internal numbers, never shown to clients.":{ru:"Внутренние цифры, клиент их не видит.",es:"Datos internos que el cliente nunca verá."},"Labor":{ru:"Работа",es:"Mano de obra"},
 "No clients yet":{ru:"Клиентов пока нет",es:"Aún no hay clientes"},"Catalog items will appear here":{ru:"Позиции каталога появятся здесь",es:"Los trabajos aparecerán aquí"},"Add reusable material prices":{ru:"Добавьте цены на материалы",es:"Añade precios de materiales"},"Add new":{ru:"Добавить",es:"Añadir"},"Work catalog":{ru:"Каталог работ",es:"Catálogo de trabajos"},
 "Export PDF":{ru:"Скачать PDF",es:"Exportar PDF"},"Send proposal":{ru:"Отправить предложение",es:"Enviar propuesta"},"Category / item":{ru:"Категория / работа",es:"Categoría / trabajo"},"Qty":{ru:"Кол-во",es:"Cant."},"Unit":{ru:"Ед.",es:"Unidad"},"Material":{ru:"Материал",es:"Material"},"Markup":{ru:"Наценка",es:"Recargo"},"Total":{ru:"Итого",es:"Total"},"Add item":{ru:"Добавить позицию",es:"Añadir partida"},"Labor cost":{ru:"Стоимость работ",es:"Coste de mano de obra"},"Material cost":{ru:"Стоимость материалов",es:"Coste de materiales"},"Total cost":{ru:"Себестоимость",es:"Coste total"},"Client total":{ru:"Итого для клиента",es:"Total cliente"},"Costs hidden in proposal":{ru:"Себестоимость скрыта",es:"Costes ocultos en la propuesta"},
 "Company settings":{ru:"Настройки компании",es:"Ajustes de empresa"},"These details appear on client proposals.":{ru:"Эти данные будут в предложениях для клиентов.",es:"Estos datos aparecen en las propuestas."},"Company name":{ru:"Название компании",es:"Nombre de empresa"},"Currency":{ru:"Валюта",es:"Moneda"},"Default markup %":{ru:"Наценка по умолчанию, %",es:"Recargo predeterminado, %"},"Target margin %":{ru:"Целевая маржа, %",es:"Margen objetivo, %"},"Phone":{ru:"Телефон",es:"Teléfono"},"Email":{ru:"Email",es:"Correo"},"Address":{ru:"Адрес",es:"Dirección"},"Save settings":{ru:"Сохранить настройки",es:"Guardar ajustes"},"Subscription":{ru:"Подписка",es:"Suscripción"},"Active plan":{ru:"Активный тариф",es:"Plan activo"},"Unlimited projects":{ru:"Безлимитные проекты",es:"Proyectos ilimitados"},"Profit tracking":{ru:"Учёт прибыли",es:"Control de beneficio"},"Client proposals & PDF":{ru:"Предложения и PDF",es:"Propuestas y PDF"},"Team roles and analytics":{ru:"Роли команды и аналитика",es:"Roles de equipo y analítica"},
 "QUICK CALCULATOR":{ru:"БЫСТРЫЙ РАСЧЁТ",es:"CÁLCULO RÁPIDO"},"Early project range":{ru:"Предварительная стоимость",es:"Rango inicial del proyecto"},"Project type":{ru:"Тип проекта",es:"Tipo de proyecto"},"Area, m²":{ru:"Площадь, м²",es:"Superficie, m²"},"Renovation level":{ru:"Уровень ремонта",es:"Nivel de reforma"},"Budget estimate based on your company settings":{ru:"Расчёт по настройкам вашей компании",es:"Estimación basada en los ajustes de tu empresa"},
 "New client":{ru:"Новый клиент",es:"Nuevo cliente"},"Add new client":{ru:"Добавить нового клиента",es:"Añadir un cliente nuevo"},"New material":{ru:"Новый материал",es:"Nuevo material"},"New estimate":{ru:"Новая смета",es:"Nuevo presupuesto"},"BUILD ESTIMATE":{ru:"СОЗДАНИЕ СМЕТЫ",es:"CREAR PRESUPUESTO"},"Project name":{ru:"Название проекта",es:"Nombre del proyecto"},"Project address":{ru:"Адрес объекта",es:"Dirección de la obra"},"Client name":{ru:"Имя клиента",es:"Nombre del cliente"},"Client address":{ru:"Адрес клиента",es:"Dirección del cliente"},"Name":{ru:"Название",es:"Nombre"},"Client":{ru:"Клиент",es:"Cliente"},"No client":{ru:"Без клиента",es:"Sin cliente"},"Purchase price":{ru:"Закупочная цена",es:"Precio de compra"},"Selling price":{ru:"Цена продажи",es:"Precio de venta"},"Supplier":{ru:"Поставщик",es:"Proveedor"},"Create":{ru:"Создать",es:"Crear"},"Saving…":{ru:"Сохранение…",es:"Guardando…"},"Try again":{ru:"Повторить",es:"Reintentar"},"Preparing your workspace":{ru:"Подготавливаем рабочее пространство",es:"Preparando tu espacio de trabajo"},"BuildEstimate is unavailable":{ru:"BuildEstimate временно недоступен",es:"BuildEstimate no está disponible"},
 "name":{ru:"название",es:"nombre"},"phone":{ru:"телефон",es:"teléfono"},"email":{ru:"email",es:"correo"},"address":{ru:"адрес",es:"dirección"},"category":{ru:"категория",es:"categoría"},"unit":{ru:"единица",es:"unidad"},"labor cost":{ru:"стоимость работ",es:"coste de mano de obra"},"material cost":{ru:"стоимость материалов",es:"coste de materiales"},"purchase price":{ru:"закупочная цена",es:"precio de compra"},"selling price":{ru:"цена продажи",es:"precio de venta"},"supplier":{ru:"поставщик",es:"proveedor"},"Duplicate":{ru:"Дублировать",es:"Duplicar"},"Delete":{ru:"Удалить",es:"Eliminar"},
 "draft":{ru:"черновик",es:"borrador"},"sent":{ru:"отправлено",es:"enviada"},"viewed":{ru:"просмотрено",es:"vista"},"negotiation":{ru:"переговоры",es:"negociación"},"accepted":{ru:"принято",es:"aceptada"},"rejected":{ru:"отклонено",es:"rechazada"},"completed":{ru:"завершено",es:"completado"},"basic":{ru:"базовый",es:"básico"},"standard":{ru:"стандарт",es:"estándar"},"premium":{ru:"премиум",es:"premium"},"luxury":{ru:"люкс",es:"lujo"},"Renovation":{ru:"Ремонт",es:"Reforma"},"New construction":{ru:"Новое строительство",es:"Obra nueva"},"Commercial fit-out":{ru:"Коммерческий ремонт",es:"Acondicionamiento comercial"},
 "DETAILED ESTIMATE":{ru:"ПОДРОБНАЯ СМЕТА",es:"PRESUPUESTO DETALLADO"},"New estimate item":{ru:"Новая позиция сметы",es:"Nueva partida"},"Item name":{ru:"Наименование работы",es:"Nombre de la partida"},"Quantity":{ru:"Количество",es:"Cantidad"},"Labor cost per unit":{ru:"Работа за единицу",es:"Mano de obra por unidad"},"Material cost per unit":{ru:"Материалы за единицу",es:"Materiales por unidad"},"Markup %":{ru:"Наценка, %",es:"Recargo, %"},"Could not save this item":{ru:"Не удалось сохранить позицию",es:"No se pudo guardar la partida"},"Close":{ru:"Закрыть",es:"Cerrar"},
 "Demolition":{ru:"Демонтаж",es:"Demolición"},"Plastering":{ru:"Штукатурные работы",es:"Enlucidos"},"Painting":{ru:"Малярные работы",es:"Pintura"},"Drywall":{ru:"Гипсокартон",es:"Paneles de yeso"},"Electrical":{ru:"Электромонтаж",es:"Electricidad"},"Plumbing":{ru:"Сантехнические работы",es:"Fontanería"},"Tiling":{ru:"Плиточные работы",es:"Alicatado"},"Flooring":{ru:"Напольные покрытия",es:"Pavimentos"},"Doors":{ru:"Двери",es:"Puertas"},"Windows":{ru:"Окна",es:"Ventanas"},"Roofing":{ru:"Кровельные работы",es:"Cubiertas"},"Facade":{ru:"Фасадные работы",es:"Fachadas"},"Insulation":{ru:"Утепление",es:"Aislamiento"},"Concrete":{ru:"Бетонные работы",es:"Hormigón"},"Masonry":{ru:"Кладочные работы",es:"Albañilería"},"HVAC":{ru:"Отопление и вентиляция",es:"Climatización"},"Other":{ru:"Другое",es:"Otros"}
};
Object.assign(labels,catalogLabels);
const reverse=new Map<string,string>();Object.entries(labels).forEach(([en,p])=>{if(!reverse.has(p.ru))reverse.set(p.ru,en);if(!reverse.has(p.es))reverse.set(p.es,en)});
export function tr(value:string,lang:Language):string{if(lang==="en")return reverse.get(value)??value;const key=reverse.get(value)??value;if(labels[key])return labels[key][lang];const search=key.match(/^Search (.+)$/);if(search)return lang==="ru"?`Поиск: ${tr(search[1],lang)}`:`Buscar ${tr(search[1],lang)}`;const margin=key.match(/^([\d.,]+)% margin$/);if(margin)return lang==="ru"?`Маржа ${margin[1]}%`:`Margen ${margin[1]}%`;return key}
export function translatePage(root:HTMLElement,lang:Language){const walk=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(walk.nextNode())nodes.push(walk.currentNode as Text);for(const node of nodes){const raw=node.nodeValue??"",trim=raw.trim();if(!trim)continue;const translated=tr(trim,lang);if(translated!==trim)node.nodeValue=raw.replace(trim,translated)}root.querySelectorAll<HTMLInputElement>('input[placeholder]').forEach(el=>{el.placeholder=tr(el.placeholder,lang)});root.querySelectorAll<HTMLElement>('[title]').forEach(el=>{const title=el.getAttribute('title');if(title)el.setAttribute('title',tr(title,lang))})}
